name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest  # You can also add ubuntu-latest or other runners if cross-platform testing is needed

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest  # Ensures latest CMake

      - name: Build and run tests (Release)
        run: make test
